defmodule PromptOnWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :prompton

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_prompton_key",
    signing_salt: "MEnb4YeF",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :prompton,
    gzip: not code_reloading?,
    only: PromptOnWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :prompton
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # The real client IP behind the gateway (Traefik) - resolves `x-forwarded-for` into
  # `conn.remote_ip` (the rate-limit key). RemoteIp **does not look at the peer, it trusts only the
  # headers**: it walks the header chain skipping hops in private/loopback ranges, picks the last
  # public IP, and falls back to the peer IP (the gateway) if there is none. Hence (1) only the one
  # header Traefik **overwrites**, `x-forwarded-for`, is read - the default's `x-client-ip` and
  # `forwarded` are untouched by Traefik, so a client could put any value in them and choose its
  # bucket - and (2) the pods must be unreachable except through the gateway (ClusterIP only). If
  # the gateway does not preserve the client IP (kube-proxy SNAT, dev's externalTrafficPolicy
  # Cluster), the chain is all private hops and every client collapses into the single gateway IP -
  # that errs toward the limit becoming global, so it is safe. OCI uses
  # `externalTrafficPolicy: Local`.
  plug RemoteIp, headers: ["x-forwarded-for"]

  # The sign-in code travels only in the POST body (`code`) and
  # `config :phoenix, :filter_parameters` masks it - no request carries a secret in its path, so
  # request logs are written as-is.
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Body cap: `POST /api/v1/logs` is ≤5MB (plan.md §6.1 - batches of ≤200 records). The other
  # APIs have a 1MB convention, but the parser is global so it stays at 5MB (lowered from the
  # default 8MB). Exceeding it raises Plug.Parsers.RequestTooLargeError -> 413.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 5_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PromptOnWeb.Router
end
