defmodule PromptOn.Repo.Migrations.EmailCodeSignIn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sign_in_codes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :code_hash, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :attempts, :bigint, null: false, default: 0
      add :consumed_at, :utc_datetime_usec
      add :requested_ip, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sign_in_codes, [:email])
  end

  def down do
    drop_if_exists index(:sign_in_codes, [:email])

    drop table(:sign_in_codes)
  end
end
