defmodule PromptOn.Repo.Migrations.OrganizationSlugsAndPersonalFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      add :personal?, :boolean, null: false, default: false
      modify :slug, :text, null: true
    end

    # Data backfill: until this release the only path that created an organization was the
    # personal organization auto-created at sign-up (no team-organization creation UI or action).
    # Personal organizations carry no slug and are addressed as `/personal`, so flip the flag and
    # clear the slug. On an empty DB this touches 0 rows — replay is unaffected.
    execute("UPDATE organizations SET \"personal?\" = true, slug = NULL", "")

    create unique_index(:organizations, [:slug],
             name: "organizations_unique_slug_index",
             where: "(slug IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      modify :slug, :text, null: false
      remove :personal?
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")
  end
end
