defmodule PromptOn.Repo.Migrations.ProviderKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:provider_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false
      add :label, :text, null: false, default: "default"
      add :secret_hint, :text
      add :last_used_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "provider_keys_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:provider_keys, [:project_id, :provider, :label],
             name: "provider_keys_unique_provider_label_index"
           )

    alter table(:provider_keys) do
      add :encrypted_secret, :binary, null: false
    end
  end

  def down do
    drop constraint(:provider_keys, "provider_keys_project_id_fkey")

    alter table(:provider_keys) do
      remove :encrypted_secret
    end

    drop_if_exists unique_index(:provider_keys, [:project_id, :provider, :label],
                     name: "provider_keys_unique_provider_label_index"
                   )

    drop table(:provider_keys)
  end
end
