defmodule PromptOn.Repo.Migrations.AddOrganizationPlanAndGenerationRetention do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :plan, :text, null: false, default: "free"
      add :judge_model, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :judge_model
      remove :plan
    end
  end
end
