defmodule PromptOn.Repo.Migrations.AddDeployments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:deployments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :revision, :bigint, null: false
      add :rules, {:array, :map}, null: false, default: []
      add :committed_by, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :use_case_id,
          references(:use_cases,
            column: :id,
            name: "deployments_use_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "deployments_environment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:deployments) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "deployments_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:deployments, [:project_id, :use_case_id, :environment_id, :revision],
             name: "deployments_unique_revision_index"
           )
  end

  def down do
    drop constraint(:deployments, "deployments_project_id_fkey")

    drop constraint(:deployments, "deployments_environment_id_fkey")

    drop constraint(:deployments, "deployments_use_case_id_fkey")

    drop_if_exists unique_index(
                     :deployments,
                     [:project_id, :use_case_id, :environment_id, :revision],
                     name: "deployments_unique_revision_index"
                   )

    alter table(:deployments) do
      remove :project_id
    end

    drop table(:deployments)
  end
end
