defmodule PromptOn.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :key_prefix, :text, null: false
      add :key_hash, :text, null: false
      add :scopes, {:array, :text}, null: false
      add :last_used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
    end

    create unique_index(:api_keys, [:key_hash], name: "api_keys_unique_key_hash_index")

    alter table(:api_keys) do
      add :environment_id, :uuid, null: false
    end

    create table(:environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:api_keys) do
      modify :environment_id,
             references(:environments,
               column: :id,
               name: "api_keys_environment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:environments) do
      add :slug, :text, null: false
      add :name, :text, null: false
      add :protected?, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
    end

    create unique_index(:environments, [:project_id, :slug],
             name: "environments_unique_slug_per_project_index"
           )

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :role, :text, null: false, default: "owner"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create unique_index(:memberships, [:organization_id, :user_id],
             name: "memberships_unique_member_index"
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:memberships) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "memberships_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:api_keys) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "api_keys_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:environments) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "environments_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:projects) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :timezone, :text, null: false, default: "Etc/UTC"
      add :dimensions, {:array, :map}, null: false, default: []
      add :payload_policy, :map, null: false
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "projects_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:projects, [:organization_id, :slug],
             name: "projects_unique_slug_per_org_index"
           )

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "memberships_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:users) do
      add :email, :citext, null: false
      add :hashed_password, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :hashed_password
      remove :email
    end

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_organization_id_fkey")

    alter table(:memberships) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop table(:tokens)

    drop constraint(:projects, "projects_organization_id_fkey")

    drop_if_exists unique_index(:projects, [:organization_id, :slug],
                     name: "projects_unique_slug_per_org_index"
                   )

    alter table(:projects) do
      remove :organization_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :payload_policy
      remove :dimensions
      remove :timezone
      remove :slug
      remove :name
    end

    drop constraint(:environments, "environments_project_id_fkey")

    alter table(:environments) do
      modify :project_id, :uuid
    end

    drop constraint(:api_keys, "api_keys_environment_id_fkey")

    drop constraint(:api_keys, "api_keys_project_id_fkey")

    alter table(:api_keys) do
      modify :project_id, :uuid
    end

    drop table(:projects)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    alter table(:memberships) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop_if_exists unique_index(:memberships, [:organization_id, :user_id],
                     name: "memberships_unique_member_index"
                   )

    drop table(:memberships)

    drop_if_exists unique_index(:environments, [:project_id, :slug],
                     name: "environments_unique_slug_per_project_index"
                   )

    alter table(:environments) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :position
      remove :protected?
      remove :name
      remove :slug
    end

    alter table(:api_keys) do
      modify :environment_id, :uuid
    end

    drop table(:environments)

    alter table(:api_keys) do
      remove :environment_id
    end

    drop_if_exists unique_index(:api_keys, [:key_hash], name: "api_keys_unique_key_hash_index")

    drop table(:api_keys)
  end
end
