defmodule PromptOn.Repo.Migrations.DeploymentPins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      remove :environment_id
    end

    alter table(:deployments) do
      add :model_id, :uuid, null: false
      add :params, :map, null: false, default: %{}
      add :provider_options, :map, null: false, default: %{}
      add :prompt_pins, :map, null: false, default: %{}
      remove :rules
    end

    alter table(:generations) do
      add :prompt, :text
      remove :rule_id
      remove :target_id
    end

    alter table(:projects) do
      remove :dimensions
    end
  end

  def down do
    alter table(:projects) do
      add :dimensions, {:array, :map}, null: false, default: []
    end

    alter table(:generations) do
      add :target_id, :uuid
      add :rule_id, :uuid
      remove :prompt
    end

    alter table(:deployments) do
      add :rules, {:array, :map}, null: false, default: []
      remove :prompt_pins
      remove :provider_options
      remove :params
      remove :model_id
    end

    alter table(:api_keys) do
      add :environment_id,
          references(:environments,
            column: :id,
            name: "api_keys_environment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end
end
