defmodule PromptOn.Repo.Migrations.EmailOnlyAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # expand (ADR 0005 / ADR 0008): password sign-in is gone, so `hashed_password` is no longer used.
  # This release only lifts the NOT NULL — dropping the column (contract) is the next release's
  # migration.
  def up do
    alter table(:users) do
      modify :hashed_password, :text, null: true
    end
  end

  def down do
    alter table(:users) do
      modify :hashed_password, :text, null: false
    end
  end
end
