defmodule PromptOn.Repo.Migrations.TrackAuthoringUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :use_case_key, :text, null: false
      add :operation, :text, null: false
      add :model, :text, null: false
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cost_usd, :decimal
      add :started_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "ai_usages_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:ai_usages, [:project_id, :started_at], name: "ai_usages_project_started_index")

    execute("""
    INSERT INTO ai_usages
      (id, project_id, use_case_key, operation, model, input_tokens, output_tokens,
       cost_usd, started_at, inserted_at)
    SELECT result.id, result.project_id, use_case.key, 'evaluation',
           COALESCE(result.judge_model, run.judge_model), result.input_tokens,
           result.output_tokens, result.cost_usd,
           COALESCE(result.scored_at, result.updated_at), now()
    FROM evaluation_results AS result
    JOIN evaluation_runs AS run
      ON run.id = result.evaluation_run_id AND run.project_id = result.project_id
    JOIN use_cases AS use_case
      ON use_case.id = run.use_case_id AND use_case.project_id = result.project_id
    WHERE result.cost_usd IS NOT NULL OR result.input_tokens IS NOT NULL
       OR result.output_tokens IS NOT NULL
    UNION ALL
    SELECT score.id, score.project_id, use_case.key, 'evaluation', score.judge_model,
           score.input_tokens, score.output_tokens, score.cost_usd, score.updated_at, now()
    FROM calibration_scores AS score
    JOIN rubrics AS rubric
      ON rubric.id = score.rubric_id AND rubric.project_id = score.project_id
    JOIN use_cases AS use_case
      ON use_case.id = rubric.use_case_id AND use_case.project_id = score.project_id
    WHERE score.status = 'ok' AND
      (score.cost_usd IS NOT NULL OR score.input_tokens IS NOT NULL
       OR score.output_tokens IS NOT NULL)
    ON CONFLICT (id) DO NOTHING
    """)
  end

  def down do
    execute("""
    SELECT 1
    """)

    drop_if_exists index(:ai_usages, [:project_id, :started_at],
                     name: "ai_usages_project_started_index"
                   )

    drop constraint(:ai_usages, "ai_usages_project_id_fkey")

    drop table(:ai_usages)
  end
end
