defmodule PromptOn.Repo.Migrations.AddPromptDraft do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:prompts) do
      add :draft, :map
    end
  end

  def down do
    alter table(:prompts) do
      remove :draft
    end
  end
end
