defmodule PromptOn.Repo.Migrations.Releases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :number, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :rules, {:array, :map}, null: false, default: []
      add :options, {:array, :map}, null: false, default: []
      add :note, :text
      add :activated_at, :utc_datetime_usec
      add :deactivated_at, :utc_datetime_usec
      add :activated_by_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :use_case_id,
          references(:use_cases,
            column: :id,
            name: "releases_use_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "releases_environment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:releases) do
      add :rolled_back_from_id,
          references(:releases,
            column: :id,
            name: "releases_rolled_back_from_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id,
          references(:projects,
            column: :id,
            name: "releases_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:releases, [:project_id, :use_case_id, :environment_id, :number],
             name: "releases_unique_number_index"
           )

    create unique_index(:releases, [:project_id, :use_case_id, :environment_id],
             name: "releases_one_active_per_target_index",
             where: "(status = 'active')"
           )

    create unique_index(:releases, [:project_id, :use_case_id, :environment_id],
             name: "releases_one_draft_per_target_index",
             where: "(status = 'draft')"
           )
  end

  def down do
    drop constraint(:releases, "releases_project_id_fkey")

    drop constraint(:releases, "releases_rolled_back_from_id_fkey")

    drop constraint(:releases, "releases_environment_id_fkey")

    drop constraint(:releases, "releases_use_case_id_fkey")

    drop_if_exists unique_index(:releases, [:project_id, :use_case_id, :environment_id],
                     name: "releases_one_draft_per_target_index"
                   )

    drop_if_exists unique_index(:releases, [:project_id, :use_case_id, :environment_id],
                     name: "releases_one_active_per_target_index"
                   )

    alter table(:releases) do
      remove :project_id
      remove :rolled_back_from_id
    end

    drop_if_exists unique_index(:releases, [:project_id, :use_case_id, :environment_id, :number],
                     name: "releases_unique_number_index"
                   )

    drop table(:releases)
  end
end
