defmodule PromptOn.Repo.Migrations.CutoverFirstPrinciplesModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:releases)

    drop table(:variants)

    alter table(:generations) do
      add :deployment_revision, :bigint
      add :target_id, :uuid
      add :deployment_id, :uuid
      remove :release_id
      remove :option_id
      remove :variant_id
    end

    alter table(:prompt_versions) do
      remove :status
      remove :published_at
    end

    alter table(:use_cases) do
      remove :selection_mode
    end
  end

  def down do
    alter table(:use_cases) do
      add :selection_mode, :text, null: false, default: "fixed"
    end

    alter table(:prompt_versions) do
      add :published_at, :utc_datetime_usec
      add :status, :text, null: false, default: "draft"
    end

    alter table(:generations) do
      add :variant_id, :uuid
      add :option_id, :uuid
      add :release_id, :uuid
      remove :deployment_id
      remove :target_id
      remove :deployment_revision
    end

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
