defmodule PromptOn.Repo.Migrations.AddManagementKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:management_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :key_prefix, :text, null: false
      add :key_hash, :text, null: false
      add :last_used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "management_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:management_keys, [:key_hash],
             name: "management_keys_unique_key_hash_index"
           )
  end

  def down do
    drop constraint(:management_keys, "management_keys_organization_id_fkey")

    drop_if_exists unique_index(:management_keys, [:key_hash],
                     name: "management_keys_unique_key_hash_index"
                   )

    drop table(:management_keys)
  end
end
