defmodule PromptOn.Repo.Migrations.UserInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :role, :text, null: false, default: "member"
      add :project_ids, {:array, :uuid}, null: false, default: []
      add :token_hash, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :accepted_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "invitations_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:invitations, [:token_hash], name: "invitations_unique_token_hash_index")

    alter table(:invitations) do
      add :inviter_id,
          references(:users,
            column: :id,
            name: "invitations_inviter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :accepted_by_id,
          references(:users,
            column: :id,
            name: "invitations_accepted_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create index(:invitations, [:organization_id, :email])

    create index(:invitations, [:expires_at])

    alter table(:memberships) do
      modify :role, :text, default: "member"
    end

    create table(:project_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_memberships_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "project_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:project_memberships, [:project_id, :user_id],
             name: "project_memberships_unique_project_member_index"
           )

    alter table(:projects) do
      add :creator_id,
          references(:users,
            column: :id,
            name: "projects_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:projects, "projects_creator_id_fkey")

    alter table(:projects) do
      remove :creator_id
    end

    drop constraint(:project_memberships, "project_memberships_user_id_fkey")

    drop constraint(:project_memberships, "project_memberships_project_id_fkey")

    drop_if_exists unique_index(:project_memberships, [:project_id, :user_id],
                     name: "project_memberships_unique_project_member_index"
                   )

    drop table(:project_memberships)

    alter table(:memberships) do
      modify :role, :text, default: "owner"
    end

    drop_if_exists index(:invitations, [:expires_at])

    drop_if_exists index(:invitations, [:organization_id, :email])

    drop constraint(:invitations, "invitations_accepted_by_id_fkey")

    drop constraint(:invitations, "invitations_inviter_id_fkey")

    drop constraint(:invitations, "invitations_organization_id_fkey")

    alter table(:invitations) do
      remove :accepted_by_id
      remove :inviter_id
    end

    drop_if_exists unique_index(:invitations, [:token_hash],
                     name: "invitations_unique_token_hash_index"
                   )

    drop table(:invitations)
  end
end
