defmodule PromptOn.Repo.Migrations.RemoveLegacyProjectNames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DROP FUNCTION IF EXISTS sync_project_description() CASCADE;
    """)

    alter table(:projects) do
      remove :name
    end
  end

  def down do
    alter table(:projects) do
      add :name, :text
    end

    execute("""
    DO $migration$
    BEGIN
      CREATE FUNCTION sync_project_description() RETURNS trigger AS $sync$
      BEGIN
        IF TG_OP = 'INSERT' THEN
          NEW.description := COALESCE(NEW.description, NULLIF(NEW.name, NEW.slug));
          NEW.name := COALESCE(NEW.description, NEW.slug);
        ELSIF NEW.description IS DISTINCT FROM OLD.description THEN
          NEW.name := COALESCE(NEW.description, NEW.slug);
        ELSIF NEW.name IS DISTINCT FROM OLD.name THEN
          NEW.description := NULLIF(NEW.name, NEW.slug);
        END IF;
        RETURN NEW;
      END;
      $sync$ LANGUAGE plpgsql;

      CREATE TRIGGER sync_project_description
      BEFORE INSERT OR UPDATE ON projects
      FOR EACH ROW EXECUTE FUNCTION sync_project_description();

      UPDATE projects
      SET description = COALESCE(description, NULLIF(name, slug)),
          name = COALESCE(description, name, slug);
    END;
    $migration$;
    """)
  end
end
