defmodule PromptOn.Repo.Migrations.OrganizationDraftModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :draft_model, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :draft_model
    end
  end
end
