defmodule PromptOn.Repo.Migrations.DeviceLoginRemovesManagementKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop table(:management_keys)

    create table(:device_authorizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :device_code_hash, :text, null: false
      add :user_code, :text, null: false
      add :client, :text, null: false
      add :key_name, :text
      add :status, :text, null: false, default: "pending"
      add :expires_at, :utc_datetime_usec, null: false
      add :last_polled_at, :utc_datetime_usec
      add :decided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "device_authorizations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create unique_index(:device_authorizations, [:device_code_hash],
             name: "device_authorizations_unique_device_code_hash_index"
           )

    create unique_index(:device_authorizations, [:user_code],
             name: "device_authorizations_unique_user_code_index"
           )

    alter table(:device_authorizations) do
      add :encrypted_token, :binary
    end
  end

  def down do
    drop constraint(:device_authorizations, "device_authorizations_user_id_fkey")

    alter table(:device_authorizations) do
      remove :encrypted_token
    end

    drop_if_exists unique_index(:device_authorizations, [:user_code],
                     name: "device_authorizations_unique_user_code_index"
                   )

    drop_if_exists unique_index(:device_authorizations, [:device_code_hash],
                     name: "device_authorizations_unique_device_code_hash_index"
                   )

    drop table(:device_authorizations)

    # Rollback would require recreating the table manually
  end
end
