defmodule PromptOn.Repo.Migrations.AddArenaMessageRequestContext do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:arena_messages) do
      add :encrypted_request_context, :binary
    end
  end

  def down do
    alter table(:arena_messages) do
      remove :encrypted_request_context
    end
  end
end
