defmodule PromptOn.Repo.Migrations.CatalogAndPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:models, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false
      add :model_id, :text, null: false
      add :display_name, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :provider_options, :map, null: false, default: %{}
      add :pricing, :map, null: false, default: %{}
      add :context_length, :bigint
      add :capabilities, {:array, :text}, null: false, default: []
      add :status, :text, null: false, default: "active"
      add :synced_at, :utc_datetime_usec
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "models_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:models, [:project_id, :provider, :model_id],
             name: "models_unique_provider_model_index"
           )

    create table(:prompt_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :number, :bigint, null: false
      add :status, :text, null: false, default: "draft"
      add :engine, :text, null: false, default: "liquid"
      add :messages, {:array, :map}, null: false, default: []
      add :text_template, :text
      add :detected_variables, {:array, :text}, null: false, default: []
      add :commit_message, :text
      add :author_id, :uuid
      add :published_at, :utc_datetime_usec
      add :content_sha256, :text, null: false
      add :tools, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :prompt_id, :uuid, null: false
    end

    alter table(:prompt_versions) do
      add :parent_version_id,
          references(:prompt_versions,
            column: :id,
            name: "prompt_versions_parent_version_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id,
          references(:projects,
            column: :id,
            name: "prompt_versions_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:prompt_versions, [:project_id, :prompt_id, :number],
             name: "prompt_versions_unique_number_per_prompt_index"
           )

    create table(:prompts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:prompt_versions) do
      modify :prompt_id,
             references(:prompts,
               column: :id,
               name: "prompt_versions_prompt_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:prompts) do
      add :name, :text, null: false, default: "default"
      add :description, :text
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :use_case_id, :uuid, null: false
    end

    alter table(:prompts) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "prompts_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:prompts, [:project_id, :use_case_id, :name],
             name: "prompts_unique_name_per_use_case_index"
           )

    create table(:use_cases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:prompts) do
      modify :use_case_id,
             references(:use_cases,
               column: :id,
               name: "prompts_use_case_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:use_cases) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :kind, :text, null: false, default: "chat"
      add :selection_mode, :text, null: false, default: "fixed"
      add :input_schema, {:array, :map}, null: false, default: []
      add :default_params, :map, null: false, default: %{}
      add :payload_policy, :map
      add :tags, {:array, :text}, null: false, default: []
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "use_cases_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:use_cases, [:project_id, :key],
             name: "use_cases_unique_key_per_project_index"
           )

    create table(:variants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :params, :map, null: false, default: %{}
      add :provider_options, :map, null: false, default: %{}
      add :description, :text
      add :tags, {:array, :text}, null: false, default: []
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :use_case_id,
          references(:use_cases,
            column: :id,
            name: "variants_use_case_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:variants) do
      add :prompt_version_id,
          references(:prompt_versions,
            column: :id,
            name: "variants_prompt_version_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :model_id,
          references(:models,
            column: :id,
            name: "variants_model_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "variants_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:variants, [:project_id, :use_case_id, :name],
             name: "variants_unique_name_per_use_case_index"
           )
  end

  def down do
    drop constraint(:variants, "variants_project_id_fkey")

    drop constraint(:variants, "variants_model_id_fkey")

    drop constraint(:variants, "variants_prompt_version_id_fkey")

    drop constraint(:variants, "variants_use_case_id_fkey")

    alter table(:variants) do
      remove :project_id
      remove :model_id
      remove :prompt_version_id
    end

    drop_if_exists unique_index(:variants, [:project_id, :use_case_id, :name],
                     name: "variants_unique_name_per_use_case_index"
                   )

    drop table(:variants)

    drop constraint(:use_cases, "use_cases_project_id_fkey")

    drop_if_exists unique_index(:use_cases, [:project_id, :key],
                     name: "use_cases_unique_key_per_project_index"
                   )

    alter table(:use_cases) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :tags
      remove :payload_policy
      remove :default_params
      remove :input_schema
      remove :selection_mode
      remove :kind
      remove :description
      remove :name
      remove :key
    end

    drop constraint(:prompts, "prompts_project_id_fkey")

    drop constraint(:prompts, "prompts_use_case_id_fkey")

    alter table(:prompts) do
      modify :use_case_id, :uuid
    end

    drop table(:use_cases)

    alter table(:prompts) do
      remove :project_id
    end

    drop_if_exists unique_index(:prompts, [:project_id, :use_case_id, :name],
                     name: "prompts_unique_name_per_use_case_index"
                   )

    alter table(:prompts) do
      remove :use_case_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :description
      remove :name
    end

    drop constraint(:prompt_versions, "prompt_versions_project_id_fkey")

    drop constraint(:prompt_versions, "prompt_versions_parent_version_id_fkey")

    drop constraint(:prompt_versions, "prompt_versions_prompt_id_fkey")

    alter table(:prompt_versions) do
      modify :prompt_id, :uuid
    end

    drop table(:prompts)

    alter table(:prompt_versions) do
      remove :project_id
      remove :parent_version_id
    end

    drop_if_exists unique_index(:prompt_versions, [:project_id, :prompt_id, :number],
                     name: "prompt_versions_unique_number_per_prompt_index"
                   )

    drop table(:prompt_versions)

    drop constraint(:models, "models_project_id_fkey")

    drop_if_exists unique_index(:models, [:project_id, :provider, :model_id],
                     name: "models_unique_provider_model_index"
                   )

    drop table(:models)
  end
end
