defmodule PromptOn.Repo.Migrations.AddArenaMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:arena_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false, default: ""
      add :status, :text, null: false, default: "ok"
      add :error_message, :text
      add :prompt_version_number, :bigint
      add :params, :map, null: false, default: %{}
      add :latency_ms, :bigint
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cost_usd, :decimal
      add :author_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :use_case_id,
          references(:use_cases,
            column: :id,
            name: "arena_messages_use_case_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :model_id,
          references(:models,
            column: :id,
            name: "arena_messages_model_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "arena_messages_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:arena_messages, [:project_id, :use_case_id, :model_id, :inserted_at, :id],
             name: "arena_messages_use_case_model_index"
           )

    alter table(:use_cases) do
      add :arena_model_ids, {:array, :uuid}, null: false, default: []
    end
  end

  def down do
    alter table(:use_cases) do
      remove :arena_model_ids
    end

    drop_if_exists index(
                     :arena_messages,
                     [:project_id, :use_case_id, :model_id, :inserted_at, :id],
                     name: "arena_messages_use_case_model_index"
                   )

    drop constraint(:arena_messages, "arena_messages_project_id_fkey")

    drop constraint(:arena_messages, "arena_messages_model_id_fkey")

    drop constraint(:arena_messages, "arena_messages_use_case_id_fkey")

    drop table(:arena_messages)
  end
end
