defmodule PromptOn.Repo.Migrations.ProviderKeysToOrganization do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  ## Reparenting BYOK provider keys from project → organization (2026-09-01)

  A **destructive column swap**: drops `provider_keys.project_id` and adds `organization_id`
  (NOT NULL). It is an exception to the expand/contract discipline of ADR 0005, justified the same
  way as the ADR 0007 cutover — there is no production deployment and dropping the dev DB was
  agreed. The migration chain replays as is on an empty DB (a NOT NULL column is added to an empty
  table, so no backfill is needed). From the next schema change on, expand/contract applies again.
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:provider_keys, [:project_id, :provider, :label],
                     name: "provider_keys_unique_provider_label_index"
                   )

    alter table(:provider_keys) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "provider_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:provider_keys, [:organization_id, :provider, :label],
             name: "provider_keys_unique_provider_label_index"
           )

    alter table(:provider_keys) do
      remove :project_id
    end
  end

  def down do
    drop constraint(:provider_keys, "provider_keys_organization_id_fkey")

    alter table(:provider_keys) do
      add :project_id,
          references(:projects,
            column: :id,
            name: "provider_keys_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    drop_if_exists unique_index(:provider_keys, [:organization_id, :provider, :label],
                     name: "provider_keys_unique_provider_label_index"
                   )

    alter table(:provider_keys) do
      remove :organization_id
    end

    create unique_index(:provider_keys, [:project_id, :provider, :label],
             name: "provider_keys_unique_provider_label_index"
           )
  end
end
