defmodule PromptOn.Repo.Migrations.Observability do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  (reordered by hand: `generations` first, then `generation_payloads` with its FK inline —
  the generated version created an empty `generations` table and altered it afterwards).
  """

  use Ecto.Migration

  def up do
    create table(:generations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :use_case_key, :text, null: false
      add :release_id, :uuid
      add :rule_id, :uuid
      add :option_id, :uuid
      add :model, :text, null: false
      add :provider, :text, null: false, default: "other"
      add :source, :text, null: false, default: "live"
      add :kind, :text, null: false, default: "chat"
      add :status, :text, null: false
      add :finish_reason, :text
      add :stop_kind, :text
      add :error_kind, :text
      add :error_message, :text
      add :latency_ms, :bigint
      add :input_tokens, :bigint
      add :output_tokens, :bigint
      add :cost_usd, :decimal
      add :cost_source, :text, null: false, default: "unknown"
      add :trace_id, :text
      add :sequence, :bigint
      add :end_user_ref, :text
      add :resolution_source, :text
      add :payload_state, :text, null: false, default: "dropped"
      add :sdk_version, :text
      add :started_at, :utc_datetime_usec, null: false

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :params, :map, null: false, default: %{}
      add :context, :map, null: false, default: %{}
      add :metadata, :map, null: false, default: %{}
      add :environment_id, :uuid
      add :use_case_id, :uuid
      add :variant_id, :uuid
      add :prompt_version_id, :uuid
      add :model_id, :uuid

      add :project_id,
          references(:projects,
            column: :id,
            name: "generations_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:generations, [:project_id, desc: :started_at, desc: :id],
             name: "generations_project_started_index"
           )

    create index(:generations, [:project_id, :use_case_id, desc: :started_at],
             name: "generations_project_use_case_started_index"
           )

    create index(:generations, [:project_id, :trace_id], name: "generations_project_trace_index")

    create index(:generations, [:project_id, :end_user_ref, desc: :started_at],
             name: "generations_project_end_user_started_index",
             where: "end_user_ref IS NOT NULL"
           )

    create index(:generations, [:received_at],
             name: "generations_received_at_brin",
             using: "BRIN"
           )

    create table(:generation_payloads, primary_key: false) do
      add :generation_id,
          references(:generations,
            column: :id,
            name: "generation_payloads_generation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false,
          primary_key: true

      add :usage_raw, :map
      add :input_sha256, :text
      add :output_sha256, :text
      add :bytes_in, :bigint
      add :bytes_out, :bigint
      add :truncated, :boolean, null: false, default: false
      add :encrypted, :boolean, null: false, default: true
      add :expires_at, :utc_datetime_usec, null: false

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "generation_payloads_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :encrypted_input, :binary
      add :encrypted_output, :binary
      add :encrypted_variables, :binary
    end

    create index(:generation_payloads, [:project_id, :expires_at],
             name: "generation_payloads_expires_at_brin",
             using: "BRIN"
           )
  end

  def down do
    drop_if_exists index(:generation_payloads, [:project_id, :expires_at],
                     name: "generation_payloads_expires_at_brin"
                   )

    drop table(:generation_payloads)

    drop_if_exists index(:generations, [:received_at], name: "generations_received_at_brin")

    drop_if_exists index(:generations, [:project_id, :end_user_ref, desc: :started_at],
                     name: "generations_project_end_user_started_index"
                   )

    drop_if_exists index(:generations, [:project_id, :trace_id],
                     name: "generations_project_trace_index"
                   )

    drop_if_exists index(:generations, [:project_id, :use_case_id, desc: :started_at],
                     name: "generations_project_use_case_started_index"
                   )

    drop_if_exists index(:generations, [:project_id, desc: :started_at, desc: :id],
                     name: "generations_project_started_index"
                   )

    drop table(:generations)
  end
end
