defmodule PromptOn.Repo.Migrations.ChatOnlyUseCases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    UPDATE use_cases
    SET archived_at = (now() AT TIME ZONE 'utc'),
        updated_at = (now() AT TIME ZONE 'utc')
    WHERE kind <> 'chat' AND archived_at IS NULL
    """)
  end

  def down do
    execute("""
    SELECT 1
    """)
  end
end
