defmodule PromptOn.Repo.Migrations.PreserveLegacyProjectAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    INSERT INTO project_memberships (id, project_id, user_id, inserted_at, updated_at)
    SELECT uuid_generate_v7(), projects.id, memberships.user_id, now(), now()
    FROM projects
    JOIN memberships ON memberships.organization_id = projects.organization_id
    WHERE memberships.role IN ('editor', 'viewer')
    ON CONFLICT (project_id, user_id) DO NOTHING
    """)
  end

  def down do
    execute("""
    SELECT 1
    """)
  end
end
